### ISSUE TITLE
"errorMessage": "Message: 'chromedriver' executable may have wrong permissions.

### ISSUE THREAD

**Issue by actioncorp3** [ManivannanMurugavel/selenium-python-aws-lambda#10]
Hello Manivannan,
Thanks for sharing the code, in the first instance I had no problems, but to the following code fragment of "lambda_function.py":

**Original:**
    driver = webdriver.Chrome (chrome_options = chrome_options)
    page_data = ""
    if 'url' en event.keys ():
        driver.get (evento ['url'])
        page_data = driver.page_source
        print (page_data)
    driver.close ()
    volver page_data

**New:**

    driver = webdriver.Chrome (chrome_options = chrome_options)
    page_data = ""
    if 'url' en event.keys ():
        driver.get (evento ['url'])
        page_data = driver.title
        print (page_data)
    driver.close ()
    volver page_data

**When testing the lambda I am getting the following error:**

{
  "errorMessage": "Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n",
  "errorType": "WebDriverException",
  "stackTrace": [
    [
      "/var/task/lambda_function.py",
      46,
      "lambda_handler",
      "driver = webdriver.Chrome(chrome_options=chrome_options)"
    ],
    [
      "/var/task/selenium/webdriver/chrome/webdriver.py",
      68,
      "__init__",
      "self.service.start()"
    ],
    [
      "/var/task/selenium/webdriver/common/service.py",
      88,
      "start",
      "os.path.basename(self.path), self.start_error_message)"
    ]
  ]
}

Any ideas? Please your help.

**Comment by actioncorp3** [comment]
I read that I must give "chmod 777 chromedriver" permissions, the zip project is in s3. By cloud9 I can't find bucket s3 to give permissions to "\bin\chromedriver". How should I do it?

**Comment by alejandroalffer** [comment]
Try to use these variables in Lambda config:

PATH:/var/task/bin
PYTHONPATH:/var/task/lib

Best regards!

**Comment by actioncorp3** [comment]
Hi @ManivannanMurugavel  alejandroalffer, 
I already have those environment variables in lambda, the error seems to be not to have permissions in chromedriver, but I don't know how to give those permissions to that file from lambda or cloud9. 

I have associated the "AmazonS3FullAccess" policy with the IAM role related to Lambda, but I am still unsuccessful...

**Comment by ManivannanMurugavel** [comment]
Hi,
     Try to set the permission in ubuntu machine and copy paste into your
lambda

**Comment by actioncorp3** [comment]
Ok, I'll try from a virtual machine with ubuntu

**Comment by actioncorp3** [comment]
Hi @ManivannanMurugavel ! 

Perform the step indicated from Ubuntu, changing the permissions to 777 of "bin / chromedriver" and "bin / headless-chromium", but now I throw the following error:

{
  "errorMessage": "Unable to import module 'lambda_function'"
}

Verify the controller and it is correct. Any ideas?

**Comment by ManivannanIkomet** [comment]
Hi @actioncorp3 ,
I forgot to add this line.
Set the executable permission to chromedrive not 777 permission
Download the chrome driver and set the executable permission using below command

```
sudo chmod a+x chromedriver
```

**Comment by actioncorp3** [comment]
Thanks @ManivannanMurugavel , it worked

**Comment by actioncorp3** [comment]
@ManivannanMurugavel have you thought about transferring it to serverless to deploy it in Cloud9? It would be a great improvement! Congratulations on the project, interesting.
