### ISSUE TITLE
Timed Out Error

### ISSUE THREAD

**Issue by eonnyhoney** [ManivannanMurugavel/selenium-python-aws-lambda#12]
Hi 🙂 

I'm trying to run this file on lambda, but this error showed up

`
{
  "errorMessage": "2021-02-16T01:48:40.456Z c9ee96ed-c1dd-46c5-bbed-fd12d512d186 Task timed out after 20.01 seconds"
}
`

This is the log
`START RequestId: c9ee96ed-c1dd-46c5-bbed-fd12d512d186 Version: $LATEST`
`Starting google.com`
`END RequestId: c9ee96ed-c1dd-46c5-bbed-fd12d512d186`
`REPORT RequestId: c9ee96ed-c1dd-46c5-bbed-fd12d512d186	Duration: 20009.43 ms	Billed Duration: 20000 ms	Memory Size: 256 MB	Max Memory Used: 256 MB	Init Duration: 56.57 ms`
`2021-02-16T01:48:40.456Z c9ee96ed-c1dd-46c5-bbed-fd12d512d186 Task timed out after 20.01 seconds`

I didn't even unzip and re-zip the file, I uploaded the very file I downloaded here.
The runtime is Python 3.6 and I also created the PATHs.

If you have any clue, please do not hesitate to let me know. Thanks!

**Comment by minseongg** [comment]
I'm not sure, but how about increasing Memory or Timeout in `Basic settings`?

How about increasing Memory or Timeout in the `Basic settings`?

I tried this today with 256MB Memory, it succeeded with 19000ms. And I tried the same thing with 1024MB Memory, it succeeded with 5000ms.

**Comment by minseongg** [comment]
How about increasing Memory or Timeout in the `Basic settings`?

I tried this today with 256MB Memory, it succeeded with 19000ms. And I tried the same thing with 1024MB Memory, it succeeded with 5000ms.

**Comment by eonnyhoney** [comment]
> How about increasing Memory or Timeout in the `Basic settings`?
> 
> I tried this today with 256MB Memory, it succeeded with 19000ms. And I tried the same thing with 1024MB Memory, it succeeded with 5000ms.

I tried it with 1024MB memory and it just worked in 5677ms! (def not an expert ;-)

guess I should close this issue.
Thank you @minseongg !
